YAML
name: Semgrep
on:
  pull_request: {}
  push:
    branches: ["main", "master"]
  workflow_dispatch: {}
permissions:
  contents: read
  security-events: write # Required for uploading SARIF to GitHub Advanced Security
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor!= 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
